### get all villains
GET http://localhost:8080/villains

### get villain by id
GET http://localhost:8080/villains/1

### find villains by prison id
GET http://localhost:8080/villains/allVillainsByPrisonId/1

### update villain
PUT http://localhost:8080/villains/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "Zbigniew",
  "lastName": "zz",
  "originCountry": "Poland",
  "deposit": 2.02,
  "dateOfConviction": "31.12.2022",
  "alive": false,
  "offense": 2
}

### create villain
POST http://localhost:8080/villains/
Content-Type: application/json

{
  "firstName": "Tomasz",
  "lastName": "Łacina",
  "prisonName": "Alcatraz",
  "deposit": 9.99,
  "dateOfConviction": "23.05.2023",
  "originCountry": "Wrocław",
  "alive": true,
  "offense": 1
}

