### get all villains
GET http://localhost:8080/prison/villains

### get villain by id
GET http://localhost:8080/prison/villains/1

### update villain
PUT http://localhost:8080/prison/villains/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "Zbigniew",
  "lastName": "Ziobro",
  "originCountry": "Poland",
  "prisonName": "Wronia",
  "dateOfConviction": "31.12.2022",
  "deposit": 2.02,
  "alive": false
}